name: boostsecurity.io

env:
    BOOST_IMAGE_NAME: justinjustin/poc
    CODEQL_LANGUAGE: python

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
    
jobs:
    boost-dev-image:
        name: Image
        if: github.event_name != 'pull_request'  # SBOM scanner only runs on default branch.
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Scan Docker Image
              uses: boostsecurityio/boostsec-scanner-github@v4
              env:
                BOOST_IMAGE_NAME: ubuntu:latest
              with:
                  api_endpoint: https://api.dev.boostsec.io
                  api_token: ${{ secrets.BOOST_API_TOKEN }}
                  registry_module: boostsecurityio/trivy-image
                  
                  
    boost-prod-image:
        name: Image2
        if: github.event_name != 'pull_request'  # SBOM scanner only runs on default branch.
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Scan Docker Image
              uses: boostsecurityio/boostsec-scanner-github@v4
              env:
                BOOST_IMAGE_NAME: jenkins/jenkins:lts-jdk11
              with:
                  api_token: ${{ secrets.BOOST_PROD_API_TOKEN }}
                  registry_module: boostsecurityio/trivy-image
                  
